[Variables]
TotalGame=14

Gamename1=Ghost recon: Wildlands 
Gamecover1=wildlands.png
Gamewall1=wildlands.jpg
Gamedir1=steam://rungameid/460930

Gamename2=Insurgency Sandstorm
Gamecover2=fallout4.png
Gamedir2=steam://rungameid/581320
Gamewall2=Insurgency-Sandstorm-keyart.jpg

Gamename3=Assassin's Creed Odysseys
Gamecover3=kerbal.png
Gamedir3=D:\Program Files\Assassin's Creed - Odyssey\ACOdyssey.exe
Gamewall3=ACO.jpg

Gamename4=Final Fantasy XV
Gamecover4=ffxv.png
Gamewall4=ffxv.jpg
Gamedir4=D:\Program Files\FFXV\ffxv_s.exe

Gamename5=Nier Automata
Gamecover5=nier.png
Gamewall5=nier.jpg
Gamedir5=D:\Program Files\NieR - Automata\NieRAutomata.exe

Gamename6=The Witcher 3: Wild Hunt
Gamecover6=witcher3.png
Gamewall6=witcher3.png
Gamedir6=D:\Program Files\The Witcher 3 - Wild Hunt\bin\x64\witcher3.exe

Gamename7=Battlefield 4
Gamecover7=bf4.png
Gamewall7=bf4.jpg
Gamedir7=D:\Program Files\Battlefield 4\bf4.exe

Gamename8=Warframe
Gamecover8=warframe.png
Gamewall8=warframe.jpg
Gamedir8=C:\Users\Finch\AppData\Local\Warframe\Downloaded\Test\Tools\Launcher.exe

Gamename9=A way out
Gamecover9=sv.png
Gamewall9=awo.jpg
Gamedir9=D:\Program Files\A Way Out\Haze1\Binaries\Win64\AWayOut.exe

Gamename10=Shadow of the Tomb Raider
Gamecover10=wd2.png
Gamewall10=image.jpg
Gamedir10=D:\Program Files\Shadow of the Tomb Raider\SOTTR.exe

Gamename11=The Sims 4
Gamecover11=sims4.png
Gamewall11=sims4.jpg
Gamedir11=D:\Program Files\The Sims 4\Game\Bin\TS4_x64.exe

Gamename12=Minecraft
Gamecover12=minecraft.png
Gamewall12=minecraft.jpg
Gamedir12=C:\Users\Finch\AppData\Roaming\.minecraft\MinecraftLauncher.exe

Gamename13=Batman: Arkham Knight
Gamecover13=arkhamknight.png
Gamewall13=batman_arkham.jpg
Gamedir13=D:\Program Files\Batman - Arkham Knight\Binaries\Win64\BatmanAK.exe

Gamename14=The Legend of Zelda: Breath of the Wild
Gamecover14=hellblade.png
Gamewall14=botw.jpg
Gamedir14="E:\roms\WiiU\Cemu.exe" "-g" "E:\roms\WiiU\rom\The Legend of Zelda Breath of the Wild\code\U-King.rpx" "-f"

Gamename15=
Gamecover15=default.png
Gamewall15=default.png
Gamedir15=

Gamename16=
Gamecover16=default.png
Gamewall16=default.png
Gamedir16=

Gamename17=
Gamecover17=default.png
Gamewall17=default.png
Gamedir17=

Gamename18=
Gamecover18=default.png
Gamewall18=default.png
Gamedir18=

Gamename19=
Gamecover19=default.png
Gamewall19=default.png
Gamedir19=

Gamename20=
Gamecover20=default.png
Gamewall20=default.png
Gamedir20=

Gamename21=
Gamecover21=default.png
Gamewall21=default.png
Gamedir21=

Gamename22=
Gamecover22=default.png
Gamewall22=default.png
Gamedir22=

Gamename23=
Gamecover23=default.png
Gamewall23=default.png
Gamedir23=

Gamename24=
Gamecover24=default.png
Gamewall24=default.png
Gamedir24=

Gamename25=
Gamecover25=default.png
Gamewall25=default.png
Gamedir25=

Gamename26=
Gamecover26=default.png
Gamewall26=default.png
Gamedir26=

Gamename27=
Gamecover27=default.png
Gamewall27=default.png
Gamedir27=

Gamename28=
Gamecover28=default.png
Gamewall28=default.png
Gamedir28=

Gamename29=
Gamecover29=default.png
Gamewall29=default.png
Gamedir29=

Gamename30=
Gamecover30=default.png
Gamewall30=default.png
Gamedir30=

Gamename31=
Gamecover31=default.png
Gamewall31=default.png
Gamedir31=
