[Variables]
SkinWidth=#SCREENAREAWIDTH#
SkinHeight=#SCREENAREAHEIGHT#

ScrollMultiplier=-0.36
CoverSolid=0,0,0,255
Color=255,255,255
LineAlpha=100
TitleScale=30
Font=Source Sans Pro ExtraLight
NameY=30
Editing=8
Mode=0
material=1
assume_size=0
BarY=0
buttonW=50
clientW=70
Title=1
endless_scroll=1
Select=9

steam=1
origin=1
uplay=1
battlenet=0
epicgames=0

keyboard=1
gamepad=1

ButtonAction=[!ActivateConfig ElegantLauncher ElegantLauncher.ini]
;ButtonAction=[!ActivateConfig ElegantLauncher\Wizard "help.ini"]
ScrollDivider=7.2
